import "./globals.css";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";

import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await prisma.category.findMany();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header categories={categories} />
        {children}
      </body>
    </html>
  );
}
