name: Run Scripts and Build Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Changez en fonction de votre projet
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: echo "Environment variables configured."

      - name: Run build script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: npm run build:out

      - name: Run populate script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: npm run populate
