name: Run Scripts and Build Next.js

on:
  schedule:
    - cron: "0 12 * * *" # S'exécute tous les jours à 12h00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Changez en fonction de votre projet
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: echo "Environment variables configured."

      - name: Run populate script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: npm run populate

      - name: Run build script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: npm run build:out

      - name: Build Next.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: npm run build
